# Generated by Django 3.2.25 on 2024-09-16 02:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total_sin_impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_total_con_impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo_id', models.PositiveIntegerField()),
                ('articulo_referencia', models.CharField(max_length=100)),
                ('articulo_nombre', models.CharField(max_length=255)),
                ('articulo_precio_sin_impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('articulo_impuesto_aplicable', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido')),
            ],
        ),
    ]
